name: DevSecOps Security Scan

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

env:
  TF_VERSION: 1.15.7

##############################################################
# Terraform Validate
##############################################################

jobs:

  terraform-validate:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: terraform init -backend=false

      - run: terraform validate

##############################################################
# TFLint
##############################################################

  tflint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4

      - run: tflint --init

      - run: tflint --recursive

##############################################################
# Checkov
##############################################################

  checkov:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform

##############################################################
# Trivy
##############################################################

  trivy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

##############################################################
# Gitleaks
##############################################################

  gitleaks:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
