name: Terraform Validate

on:
  push:
    branches:
      - main
      - develop
      - feature/**

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  terraform-validate:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
